schema {
  query: RootQueryType
}

enum MappingSortField {
  ID
  SUBSPLEASE_ID
  TVDB_ID
  TVDB_TYPE
  CANDIDATE_TVDB_ID
  CANDIDATE_TVDB_TYPE
  STATUS
  MATCH_CONFIDENCE
  MATCH_REASONING
  MATCH_METHOD
  MATCHED_AT
}

"A keyset page of :mapping"
type KeysetPageOfMapping {
  "Total count on all pages"
  count: Int

  "The records contained in the page"
  results: [Mapping!]

  "The first keyset in the results"
  startKeyset: String

  "The last keyset in the results"
  endKeyset: String
}

input MappingFilterMatchedAt {
  isNil: Boolean
  eq: DateTime
  notEq: DateTime
  in: [DateTime]
  lessThan: DateTime
  greaterThan: DateTime
  lessThanOrEqual: DateTime
  greaterThanOrEqual: DateTime
  isDistinctFrom: DateTime
  isNotDistinctFrom: DateTime
  rangeAdjacent: DateTime
  rangeContains: String
  rangeOverlaps: DateTime
}

input MappingFilterMatchMethod {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
}

input MappingFilterMatchReasoning {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input MappingFilterMatchConfidence {
  isNil: Boolean
  eq: Float
  notEq: Float
  in: [Float]
  lessThan: Float
  greaterThan: Float
  lessThanOrEqual: Float
  greaterThanOrEqual: Float
  isDistinctFrom: Float
  isNotDistinctFrom: Float
  rangeAdjacent: Float
  rangeContains: String
  rangeOverlaps: Float
}

input MappingFilterStatus {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
}

input MappingFilterCandidateTvdbType {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
}

input MappingFilterCandidateTvdbId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input MappingFilterTvdbType {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
}

input MappingFilterTvdbId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input MappingFilterSubspleaseId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int!]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input MappingFilterId {
  isNil: Boolean
  eq: ID
  notEq: ID
  in: [ID!]
  lessThan: ID
  greaterThan: ID
  lessThanOrEqual: ID
  greaterThanOrEqual: ID
  isDistinctFrom: ID
  isNotDistinctFrom: ID
  rangeAdjacent: ID
  rangeContains: String
  rangeOverlaps: ID
}

input MappingFilterInput {
  and: [MappingFilterInput!]
  or: [MappingFilterInput!]
  not: [MappingFilterInput!]
  id: MappingFilterId
  subspleaseId: MappingFilterSubspleaseId
  tvdbId: MappingFilterTvdbId
  tvdbType: MappingFilterTvdbType
  candidateTvdbId: MappingFilterCandidateTvdbId
  candidateTvdbType: MappingFilterCandidateTvdbType
  status: MappingFilterStatus
  matchConfidence: MappingFilterMatchConfidence
  matchReasoning: MappingFilterMatchReasoning
  matchMethod: MappingFilterMatchMethod
  matchedAt: MappingFilterMatchedAt
  subspleaseShow: ShowFilterInput
  tvdbSeries: TvdbSeriesFilterInput
  tvdbMovie: TvdbMovieFilterInput
}

input MappingSortInput {
  order: SortOrder
  field: MappingSortField!
}

type Mapping {
  id: ID!
  subspleaseId: Int!
  tvdbId: Int
  tvdbType: String
  candidateTvdbId: Int
  candidateTvdbType: String
  status: String!
  matchConfidence: Float
  matchReasoning: String
  matchMethod: String
  matchedAt: DateTime
  subspleaseShow: Show
  tvdbSeries: TvdbSeries
  tvdbMovie: TvdbMovie
}

enum SortOrder {
  DESC
  DESC_NULLS_FIRST
  DESC_NULLS_LAST
  ASC
  ASC_NULLS_FIRST
  ASC_NULLS_LAST
}

enum ScheduleEntrySortField {
  ID
  SLUG
  TITLE
  WEEKDAY
  SCHEDULED_TIME
  IMAGE_URL
  AIRED
  OBSERVED_AT
  SHOW_ID
}

"A keyset page of :schedule_entry"
type KeysetPageOfScheduleEntry {
  "Total count on all pages"
  count: Int

  "The records contained in the page"
  results: [ScheduleEntry!]

  "The first keyset in the results"
  startKeyset: String

  "The last keyset in the results"
  endKeyset: String
}

input ScheduleEntryFilterShowId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input ScheduleEntryFilterObservedAt {
  isNil: Boolean
  eq: DateTime
  notEq: DateTime
  in: [DateTime!]
  lessThan: DateTime
  greaterThan: DateTime
  lessThanOrEqual: DateTime
  greaterThanOrEqual: DateTime
  isDistinctFrom: DateTime
  isNotDistinctFrom: DateTime
  rangeAdjacent: DateTime
  rangeContains: String
  rangeOverlaps: DateTime
}

input ScheduleEntryFilterAired {
  isNil: Boolean
  eq: Boolean
  notEq: Boolean
  in: [Boolean!]
  lessThan: Boolean
  greaterThan: Boolean
  lessThanOrEqual: Boolean
  greaterThanOrEqual: Boolean
  isDistinctFrom: Boolean
  isNotDistinctFrom: Boolean
  rangeAdjacent: Boolean
  rangeContains: String
  rangeOverlaps: Boolean
}

input ScheduleEntryFilterImageUrl {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ScheduleEntryFilterScheduledTime {
  isNil: Boolean
  eq: Time
  notEq: Time
  in: [Time!]
  lessThan: Time
  greaterThan: Time
  lessThanOrEqual: Time
  greaterThanOrEqual: Time
  isDistinctFrom: Time
  isNotDistinctFrom: Time
  rangeAdjacent: Time
  rangeContains: String
  rangeOverlaps: Time
}

input ScheduleEntryFilterWeekday {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ScheduleEntryFilterTitle {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ScheduleEntryFilterSlug {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ScheduleEntryFilterId {
  isNil: Boolean
  eq: ID
  notEq: ID
  in: [ID!]
  lessThan: ID
  greaterThan: ID
  lessThanOrEqual: ID
  greaterThanOrEqual: ID
  isDistinctFrom: ID
  isNotDistinctFrom: ID
  rangeAdjacent: ID
  rangeContains: String
  rangeOverlaps: ID
}

input ScheduleEntryFilterInput {
  and: [ScheduleEntryFilterInput!]
  or: [ScheduleEntryFilterInput!]
  not: [ScheduleEntryFilterInput!]
  id: ScheduleEntryFilterId
  slug: ScheduleEntryFilterSlug
  title: ScheduleEntryFilterTitle
  weekday: ScheduleEntryFilterWeekday
  scheduledTime: ScheduleEntryFilterScheduledTime
  imageUrl: ScheduleEntryFilterImageUrl
  aired: ScheduleEntryFilterAired
  observedAt: ScheduleEntryFilterObservedAt
  showId: ScheduleEntryFilterShowId
  show: ShowFilterInput
}

input ScheduleEntrySortInput {
  order: SortOrder
  field: ScheduleEntrySortField!
}

type ScheduleEntry {
  id: ID!
  slug: String!
  title: String!
  weekday: String!
  scheduledTime: Time!
  imageUrl: String
  aired: Boolean!
  observedAt: DateTime!
  showId: Int
  show: Show
}

enum DownloadSortField {
  ID
  RESOLUTION
  TORRENT_URL
  MAGNET_URI
  XDCC
  RELEASE_ID
}

input DownloadFilterReleaseId {
  isNil: Boolean
  eq: ID
  notEq: ID
  in: [ID!]
  lessThan: ID
  greaterThan: ID
  lessThanOrEqual: ID
  greaterThanOrEqual: ID
  isDistinctFrom: ID
  isNotDistinctFrom: ID
  rangeAdjacent: ID
  rangeContains: String
  rangeOverlaps: ID
}

input DownloadFilterXdcc {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input DownloadFilterMagnetUri {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input DownloadFilterTorrentUrl {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input DownloadFilterResolution {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input DownloadFilterId {
  isNil: Boolean
  eq: ID
  notEq: ID
  in: [ID!]
  lessThan: ID
  greaterThan: ID
  lessThanOrEqual: ID
  greaterThanOrEqual: ID
  isDistinctFrom: ID
  isNotDistinctFrom: ID
  rangeAdjacent: ID
  rangeContains: String
  rangeOverlaps: ID
}

input DownloadFilterInput {
  and: [DownloadFilterInput!]
  or: [DownloadFilterInput!]
  not: [DownloadFilterInput!]
  id: DownloadFilterId
  resolution: DownloadFilterResolution
  torrentUrl: DownloadFilterTorrentUrl
  magnetUri: DownloadFilterMagnetUri
  xdcc: DownloadFilterXdcc
  releaseId: DownloadFilterReleaseId
  release: ReleaseFilterInput
}

input DownloadSortInput {
  order: SortOrder
  field: DownloadSortField!
}

type Download {
  id: ID!
  resolution: String!
  torrentUrl: String
  magnetUri: String
  xdcc: String
  releaseId: ID!
  release: Release!
}

enum ReleaseSortField {
  ID
  KIND
  NAME
  EPISODE
  SOURCE_DATE
  RELEASED_AT
  RAW_TIME
  SHOW_ID
}

"A keyset page of :release"
type KeysetPageOfRelease {
  "Total count on all pages"
  count: Int

  "The records contained in the page"
  results: [Release!]

  "The first keyset in the results"
  startKeyset: String

  "The last keyset in the results"
  endKeyset: String
}

input ReleaseFilterShowId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int!]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input ReleaseFilterRawTime {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ReleaseFilterReleasedAt {
  isNil: Boolean
  eq: DateTime
  notEq: DateTime
  in: [DateTime]
  lessThan: DateTime
  greaterThan: DateTime
  lessThanOrEqual: DateTime
  greaterThanOrEqual: DateTime
  isDistinctFrom: DateTime
  isNotDistinctFrom: DateTime
  rangeAdjacent: DateTime
  rangeContains: String
  rangeOverlaps: DateTime
}

input ReleaseFilterSourceDate {
  isNil: Boolean
  eq: Date
  notEq: Date
  in: [Date]
  lessThan: Date
  greaterThan: Date
  lessThanOrEqual: Date
  greaterThanOrEqual: Date
  isDistinctFrom: Date
  isNotDistinctFrom: Date
  rangeAdjacent: Date
  rangeContains: String
  rangeOverlaps: Date
}

input ReleaseFilterEpisode {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ReleaseFilterName {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ReleaseFilterKind {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
}

input ReleaseFilterId {
  isNil: Boolean
  eq: ID
  notEq: ID
  in: [ID!]
  lessThan: ID
  greaterThan: ID
  lessThanOrEqual: ID
  greaterThanOrEqual: ID
  isDistinctFrom: ID
  isNotDistinctFrom: ID
  rangeAdjacent: ID
  rangeContains: String
  rangeOverlaps: ID
}

input ReleaseFilterInput {
  and: [ReleaseFilterInput!]
  or: [ReleaseFilterInput!]
  not: [ReleaseFilterInput!]
  id: ReleaseFilterId
  kind: ReleaseFilterKind
  name: ReleaseFilterName
  episode: ReleaseFilterEpisode
  sourceDate: ReleaseFilterSourceDate
  releasedAt: ReleaseFilterReleasedAt
  rawTime: ReleaseFilterRawTime
  showId: ReleaseFilterShowId
  show: ShowFilterInput
  downloads: DownloadFilterInput
}

input ReleaseSortInput {
  order: SortOrder
  field: ReleaseSortField!
}

type Release {
  id: ID!
  kind: String!
  name: String!
  episode: String!
  sourceDate: Date
  releasedAt: DateTime
  rawTime: String
  showId: Int!
  show: Show!
  downloads(
    "How to sort the records in the response"
    sort: [DownloadSortInput]

    "A filter to limit the results"
    filter: DownloadFilterInput

    "The number of records to return."
    limit: Int

    "The number of records to skip."
    offset: Int
  ): [Download!]!
}

enum ShowSortField {
  ID
  SLUG
  NAME
  SYNOPSIS
  IMAGE_URL
  FETCHED_AT
}

"A keyset page of :show"
type KeysetPageOfShow {
  "Total count on all pages"
  count: Int

  "The records contained in the page"
  results: [Show!]

  "The first keyset in the results"
  startKeyset: String

  "The last keyset in the results"
  endKeyset: String
}

input ShowFilterFetchedAt {
  isNil: Boolean
  eq: DateTime
  notEq: DateTime
  in: [DateTime!]
  lessThan: DateTime
  greaterThan: DateTime
  lessThanOrEqual: DateTime
  greaterThanOrEqual: DateTime
  isDistinctFrom: DateTime
  isNotDistinctFrom: DateTime
  rangeAdjacent: DateTime
  rangeContains: String
  rangeOverlaps: DateTime
}

input ShowFilterImageUrl {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ShowFilterSynopsis {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ShowFilterName {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ShowFilterSlug {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input ShowFilterId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int!]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input ShowFilterInput {
  and: [ShowFilterInput!]
  or: [ShowFilterInput!]
  not: [ShowFilterInput!]
  id: ShowFilterId
  slug: ShowFilterSlug
  name: ShowFilterName
  synopsis: ShowFilterSynopsis
  imageUrl: ShowFilterImageUrl
  fetchedAt: ShowFilterFetchedAt
  releases: ReleaseFilterInput
  mapping: MappingFilterInput
}

input ShowSortInput {
  order: SortOrder
  field: ShowSortField!
}

type Show {
  id: ID!
  slug: String!
  name: String!
  synopsis: String
  imageUrl: String
  fetchedAt: DateTime!
  releases(
    "How to sort the records in the response"
    sort: [ReleaseSortInput]

    "A filter to limit the results"
    filter: ReleaseFilterInput

    "The number of records to return."
    limit: Int

    "The number of records to skip."
    offset: Int
  ): [Release!]!
  mapping: Mapping
}

enum TvdbArtworkSortField {
  ID
  ARTWORK_TYPE
  LANGUAGE
  IMAGE_URL
  THUMBNAIL_URL
  INCLUDES_TEXT
  SCORE
  WIDTH
  HEIGHT
  SERIES_ID
}

"A keyset page of :tvdb_artwork"
type KeysetPageOfTvdbArtwork {
  "Total count on all pages"
  count: Int

  "The records contained in the page"
  results: [TvdbArtwork!]

  "The first keyset in the results"
  startKeyset: String

  "The last keyset in the results"
  endKeyset: String
}

input TvdbArtworkFilterSeriesId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int!]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbArtworkFilterHeight {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbArtworkFilterWidth {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbArtworkFilterScore {
  isNil: Boolean
  eq: Float
  notEq: Float
  in: [Float]
  lessThan: Float
  greaterThan: Float
  lessThanOrEqual: Float
  greaterThanOrEqual: Float
  isDistinctFrom: Float
  isNotDistinctFrom: Float
  rangeAdjacent: Float
  rangeContains: String
  rangeOverlaps: Float
}

input TvdbArtworkFilterIncludesText {
  isNil: Boolean
  eq: Boolean
  notEq: Boolean
  in: [Boolean]
  lessThan: Boolean
  greaterThan: Boolean
  lessThanOrEqual: Boolean
  greaterThanOrEqual: Boolean
  isDistinctFrom: Boolean
  isNotDistinctFrom: Boolean
  rangeAdjacent: Boolean
  rangeContains: String
  rangeOverlaps: Boolean
}

input TvdbArtworkFilterThumbnailUrl {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbArtworkFilterImageUrl {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbArtworkFilterLanguage {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbArtworkFilterArtworkType {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbArtworkFilterId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int!]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbArtworkFilterInput {
  and: [TvdbArtworkFilterInput!]
  or: [TvdbArtworkFilterInput!]
  not: [TvdbArtworkFilterInput!]
  id: TvdbArtworkFilterId
  artworkType: TvdbArtworkFilterArtworkType
  language: TvdbArtworkFilterLanguage
  imageUrl: TvdbArtworkFilterImageUrl
  thumbnailUrl: TvdbArtworkFilterThumbnailUrl
  includesText: TvdbArtworkFilterIncludesText
  score: TvdbArtworkFilterScore
  width: TvdbArtworkFilterWidth
  height: TvdbArtworkFilterHeight
  seriesId: TvdbArtworkFilterSeriesId
  series: TvdbSeriesFilterInput
}

input TvdbArtworkSortInput {
  order: SortOrder
  field: TvdbArtworkSortField!
}

type TvdbArtwork {
  id: ID!
  artworkType: Int
  language: String
  imageUrl: String!
  thumbnailUrl: String
  includesText: Boolean
  score: Float
  width: Int
  height: Int
  seriesId: Int!
  series: TvdbSeries!
}

enum TvdbSeasonSortField {
  ID
  NUMBER
  NAME
  IMAGE_URL
  OVERVIEW
  TYPE_ID
  TYPE_NAME
  SERIES_ID
}

"A keyset page of :tvdb_season"
type KeysetPageOfTvdbSeason {
  "Total count on all pages"
  count: Int

  "The records contained in the page"
  results: [TvdbSeason!]

  "The first keyset in the results"
  startKeyset: String

  "The last keyset in the results"
  endKeyset: String
}

input TvdbSeasonFilterSeriesId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int!]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbSeasonFilterTypeName {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeasonFilterTypeId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbSeasonFilterOverview {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeasonFilterImageUrl {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeasonFilterName {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeasonFilterNumber {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbSeasonFilterId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int!]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbSeasonFilterInput {
  and: [TvdbSeasonFilterInput!]
  or: [TvdbSeasonFilterInput!]
  not: [TvdbSeasonFilterInput!]
  id: TvdbSeasonFilterId
  number: TvdbSeasonFilterNumber
  name: TvdbSeasonFilterName
  imageUrl: TvdbSeasonFilterImageUrl
  overview: TvdbSeasonFilterOverview
  typeId: TvdbSeasonFilterTypeId
  typeName: TvdbSeasonFilterTypeName
  seriesId: TvdbSeasonFilterSeriesId
  series: TvdbSeriesFilterInput
}

input TvdbSeasonSortInput {
  order: SortOrder
  field: TvdbSeasonSortField!
}

type TvdbSeason {
  id: ID!
  number: Int
  name: String
  imageUrl: String
  overview: String
  typeId: Int
  typeName: String
  seriesId: Int!
  series: TvdbSeries!
}

enum TvdbMovieSortField {
  ID
  NAME
  SLUG
  OVERVIEW
  IMAGE_URL
  FIRST_RELEASED
  YEAR
  STATUS_ID
  STATUS_NAME
  ORIGINAL_COUNTRY
  ORIGINAL_LANGUAGE
  RUNTIME
  SCORE
  FETCHED_AT
}

"A keyset page of :tvdb_movie"
type KeysetPageOfTvdbMovie {
  "Total count on all pages"
  count: Int

  "The records contained in the page"
  results: [TvdbMovie!]

  "The first keyset in the results"
  startKeyset: String

  "The last keyset in the results"
  endKeyset: String
}

input TvdbMovieFilterFetchedAt {
  isNil: Boolean
  eq: DateTime
  notEq: DateTime
  in: [DateTime!]
  lessThan: DateTime
  greaterThan: DateTime
  lessThanOrEqual: DateTime
  greaterThanOrEqual: DateTime
  isDistinctFrom: DateTime
  isNotDistinctFrom: DateTime
  rangeAdjacent: DateTime
  rangeContains: String
  rangeOverlaps: DateTime
}

input TvdbMovieFilterScore {
  isNil: Boolean
  eq: Float
  notEq: Float
  in: [Float]
  lessThan: Float
  greaterThan: Float
  lessThanOrEqual: Float
  greaterThanOrEqual: Float
  isDistinctFrom: Float
  isNotDistinctFrom: Float
  rangeAdjacent: Float
  rangeContains: String
  rangeOverlaps: Float
}

input TvdbMovieFilterRuntime {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbMovieFilterOriginalLanguage {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbMovieFilterOriginalCountry {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbMovieFilterStatusName {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbMovieFilterStatusId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbMovieFilterYear {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbMovieFilterFirstReleased {
  isNil: Boolean
  eq: Date
  notEq: Date
  in: [Date]
  lessThan: Date
  greaterThan: Date
  lessThanOrEqual: Date
  greaterThanOrEqual: Date
  isDistinctFrom: Date
  isNotDistinctFrom: Date
  rangeAdjacent: Date
  rangeContains: String
  rangeOverlaps: Date
}

input TvdbMovieFilterImageUrl {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbMovieFilterOverview {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbMovieFilterSlug {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbMovieFilterName {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbMovieFilterId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int!]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbMovieFilterInput {
  and: [TvdbMovieFilterInput!]
  or: [TvdbMovieFilterInput!]
  not: [TvdbMovieFilterInput!]
  id: TvdbMovieFilterId
  name: TvdbMovieFilterName
  slug: TvdbMovieFilterSlug
  overview: TvdbMovieFilterOverview
  imageUrl: TvdbMovieFilterImageUrl
  firstReleased: TvdbMovieFilterFirstReleased
  year: TvdbMovieFilterYear
  statusId: TvdbMovieFilterStatusId
  statusName: TvdbMovieFilterStatusName
  originalCountry: TvdbMovieFilterOriginalCountry
  originalLanguage: TvdbMovieFilterOriginalLanguage
  runtime: TvdbMovieFilterRuntime
  score: TvdbMovieFilterScore
  fetchedAt: TvdbMovieFilterFetchedAt
  mappings: MappingFilterInput
}

input TvdbMovieSortInput {
  order: SortOrder
  field: TvdbMovieSortField!
}

type TvdbMovie {
  id: ID!
  name: String!
  slug: String
  overview: String
  imageUrl: String
  firstReleased: Date
  year: String
  statusId: Int
  statusName: String
  originalCountry: String
  originalLanguage: String
  runtime: Int
  score: Float
  fetchedAt: DateTime!
  mappings(
    "How to sort the records in the response"
    sort: [MappingSortInput]

    "A filter to limit the results"
    filter: MappingFilterInput

    "The number of records to return."
    limit: Int

    "The number of records to skip."
    offset: Int
  ): [Mapping!]!
}

enum TvdbSeriesSortField {
  ID
  NAME
  SLUG
  OVERVIEW
  IMAGE_URL
  FIRST_AIRED
  LAST_AIRED
  NEXT_AIRED
  YEAR
  STATUS_ID
  STATUS_NAME
  ORIGINAL_COUNTRY
  ORIGINAL_LANGUAGE
  AVERAGE_RUNTIME
  SCORE
  FETCHED_AT
}

"A keyset page of :tvdb_series"
type KeysetPageOfTvdbSeries {
  "Total count on all pages"
  count: Int

  "The records contained in the page"
  results: [TvdbSeries!]

  "The first keyset in the results"
  startKeyset: String

  "The last keyset in the results"
  endKeyset: String
}

input TvdbSeriesFilterFetchedAt {
  isNil: Boolean
  eq: DateTime
  notEq: DateTime
  in: [DateTime!]
  lessThan: DateTime
  greaterThan: DateTime
  lessThanOrEqual: DateTime
  greaterThanOrEqual: DateTime
  isDistinctFrom: DateTime
  isNotDistinctFrom: DateTime
  rangeAdjacent: DateTime
  rangeContains: String
  rangeOverlaps: DateTime
}

input TvdbSeriesFilterScore {
  isNil: Boolean
  eq: Float
  notEq: Float
  in: [Float]
  lessThan: Float
  greaterThan: Float
  lessThanOrEqual: Float
  greaterThanOrEqual: Float
  isDistinctFrom: Float
  isNotDistinctFrom: Float
  rangeAdjacent: Float
  rangeContains: String
  rangeOverlaps: Float
}

input TvdbSeriesFilterAverageRuntime {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbSeriesFilterOriginalLanguage {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeriesFilterOriginalCountry {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeriesFilterStatusName {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeriesFilterStatusId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbSeriesFilterYear {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeriesFilterNextAired {
  isNil: Boolean
  eq: Date
  notEq: Date
  in: [Date]
  lessThan: Date
  greaterThan: Date
  lessThanOrEqual: Date
  greaterThanOrEqual: Date
  isDistinctFrom: Date
  isNotDistinctFrom: Date
  rangeAdjacent: Date
  rangeContains: String
  rangeOverlaps: Date
}

input TvdbSeriesFilterLastAired {
  isNil: Boolean
  eq: Date
  notEq: Date
  in: [Date]
  lessThan: Date
  greaterThan: Date
  lessThanOrEqual: Date
  greaterThanOrEqual: Date
  isDistinctFrom: Date
  isNotDistinctFrom: Date
  rangeAdjacent: Date
  rangeContains: String
  rangeOverlaps: Date
}

input TvdbSeriesFilterFirstAired {
  isNil: Boolean
  eq: Date
  notEq: Date
  in: [Date]
  lessThan: Date
  greaterThan: Date
  lessThanOrEqual: Date
  greaterThanOrEqual: Date
  isDistinctFrom: Date
  isNotDistinctFrom: Date
  rangeAdjacent: Date
  rangeContains: String
  rangeOverlaps: Date
}

input TvdbSeriesFilterImageUrl {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeriesFilterOverview {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeriesFilterSlug {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeriesFilterName {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
  like: String
  ilike: String
}

input TvdbSeriesFilterId {
  isNil: Boolean
  eq: Int
  notEq: Int
  in: [Int!]
  lessThan: Int
  greaterThan: Int
  lessThanOrEqual: Int
  greaterThanOrEqual: Int
  isDistinctFrom: Int
  isNotDistinctFrom: Int
  rangeAdjacent: Int
  rangeContains: String
  rangeOverlaps: Int
}

input TvdbSeriesFilterInput {
  and: [TvdbSeriesFilterInput!]
  or: [TvdbSeriesFilterInput!]
  not: [TvdbSeriesFilterInput!]
  id: TvdbSeriesFilterId
  name: TvdbSeriesFilterName
  slug: TvdbSeriesFilterSlug
  overview: TvdbSeriesFilterOverview
  imageUrl: TvdbSeriesFilterImageUrl
  firstAired: TvdbSeriesFilterFirstAired
  lastAired: TvdbSeriesFilterLastAired
  nextAired: TvdbSeriesFilterNextAired
  year: TvdbSeriesFilterYear
  statusId: TvdbSeriesFilterStatusId
  statusName: TvdbSeriesFilterStatusName
  originalCountry: TvdbSeriesFilterOriginalCountry
  originalLanguage: TvdbSeriesFilterOriginalLanguage
  averageRuntime: TvdbSeriesFilterAverageRuntime
  score: TvdbSeriesFilterScore
  fetchedAt: TvdbSeriesFilterFetchedAt
  seasons: TvdbSeasonFilterInput
  artworks: TvdbArtworkFilterInput
  mappings: MappingFilterInput
}

input TvdbSeriesSortInput {
  order: SortOrder
  field: TvdbSeriesSortField!
}

type TvdbSeries {
  id: ID!
  name: String!
  slug: String
  overview: String
  imageUrl: String
  firstAired: Date
  lastAired: Date
  nextAired: Date
  year: String
  statusId: Int
  statusName: String
  originalCountry: String
  originalLanguage: String
  averageRuntime: Int
  score: Float
  fetchedAt: DateTime!
  seasons(
    "How to sort the records in the response"
    sort: [TvdbSeasonSortInput]

    "A filter to limit the results"
    filter: TvdbSeasonFilterInput

    "The number of records to return."
    limit: Int

    "The number of records to skip."
    offset: Int
  ): [TvdbSeason!]!
  artworks(
    "How to sort the records in the response"
    sort: [TvdbArtworkSortInput]

    "A filter to limit the results"
    filter: TvdbArtworkFilterInput

    "The number of records to return."
    limit: Int

    "The number of records to skip."
    offset: Int
  ): [TvdbArtwork!]!
  mappings(
    "How to sort the records in the response"
    sort: [MappingSortInput]

    "A filter to limit the results"
    filter: MappingFilterInput

    "The number of records to return."
    limit: Int

    "The number of records to skip."
    offset: Int
  ): [Mapping!]!
}

type RootQueryType {
  tvdbSeries(
    "The id of the record"
    id: ID!
  ): TvdbSeries
  tvdbSeriesList(
    "How to sort the records in the response"
    sort: [TvdbSeriesSortInput]

    "A filter to limit the results"
    filter: TvdbSeriesFilterInput

    "The number of records to return from the beginning. Maximum 250"
    first: Int

    "Show records before the specified keyset."
    before: String

    "Show records after the specified keyset."
    after: String

    "The number of records to return to the end. Maximum 250"
    last: Int
  ): KeysetPageOfTvdbSeries
  tvdbMovie(
    "The id of the record"
    id: ID!
  ): TvdbMovie
  tvdbMovieList(
    "How to sort the records in the response"
    sort: [TvdbMovieSortInput]

    "A filter to limit the results"
    filter: TvdbMovieFilterInput

    "The number of records to return from the beginning. Maximum 250"
    first: Int

    "Show records before the specified keyset."
    before: String

    "Show records after the specified keyset."
    after: String

    "The number of records to return to the end. Maximum 250"
    last: Int
  ): KeysetPageOfTvdbMovie
  tvdbSeasons(
    "How to sort the records in the response"
    sort: [TvdbSeasonSortInput]

    "A filter to limit the results"
    filter: TvdbSeasonFilterInput

    "The number of records to return from the beginning. Maximum 250"
    first: Int

    "Show records before the specified keyset."
    before: String

    "Show records after the specified keyset."
    after: String

    "The number of records to return to the end. Maximum 250"
    last: Int
  ): KeysetPageOfTvdbSeason
  tvdbArtworks(
    "How to sort the records in the response"
    sort: [TvdbArtworkSortInput]

    "A filter to limit the results"
    filter: TvdbArtworkFilterInput

    "The number of records to return from the beginning. Maximum 250"
    first: Int

    "Show records before the specified keyset."
    before: String

    "Show records after the specified keyset."
    after: String

    "The number of records to return to the end. Maximum 250"
    last: Int
  ): KeysetPageOfTvdbArtwork
  show(
    "The id of the record"
    id: ID!
  ): Show
  shows(
    "How to sort the records in the response"
    sort: [ShowSortInput]

    "A filter to limit the results"
    filter: ShowFilterInput

    "The number of records to return from the beginning. Maximum 250"
    first: Int

    "Show records before the specified keyset."
    before: String

    "Show records after the specified keyset."
    after: String

    "The number of records to return to the end. Maximum 250"
    last: Int
  ): KeysetPageOfShow
  release(
    "The id of the record"
    id: ID!
  ): Release
  releases(
    "How to sort the records in the response"
    sort: [ReleaseSortInput]

    "A filter to limit the results"
    filter: ReleaseFilterInput

    "The number of records to return from the beginning. Maximum 250"
    first: Int

    "Show records before the specified keyset."
    before: String

    "Show records after the specified keyset."
    after: String

    "The number of records to return to the end. Maximum 250"
    last: Int
  ): KeysetPageOfRelease
  scheduleEntries(
    "How to sort the records in the response"
    sort: [ScheduleEntrySortInput]

    "A filter to limit the results"
    filter: ScheduleEntryFilterInput

    "The number of records to return from the beginning. Maximum 250"
    first: Int

    "Show records before the specified keyset."
    before: String

    "Show records after the specified keyset."
    after: String

    "The number of records to return to the end. Maximum 250"
    last: Int
  ): KeysetPageOfScheduleEntry
  mapping(
    "The id of the record"
    id: ID!
  ): Mapping
  mappings(
    "How to sort the records in the response"
    sort: [MappingSortInput]

    "A filter to limit the results"
    filter: MappingFilterInput

    "The number of records to return from the beginning. Maximum 250"
    first: Int

    "Show records before the specified keyset."
    before: String

    "Show records after the specified keyset."
    after: String

    "The number of records to return to the end. Maximum 250"
    last: Int
  ): KeysetPageOfMapping
}

"""
The `DateTime` scalar type represents a date and time in the UTC
timezone. The DateTime appears in a JSON response as an ISO8601 formatted
string, including UTC timezone ("Z"). The parsed date and time string will
be converted to UTC if there is an offset.
"""
scalar DateTime

"""
The `Date` scalar type represents a date. The Date appears in a JSON
response as an ISO8601 formatted string, without a time component.
"""
scalar Date

"""
The `Time` scalar type represents a time. The Time appears in a JSON
response as an ISO8601 formatted string, without a date component.
"""
scalar Time
