defmodule AnimeData.Repo.Migrations.InitialSubsplease do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS subsplease")

    create table(:downloads, primary_key: false, prefix: "subsplease") do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :resolution, :text, null: false
      add :torrent_url, :text
      add :magnet_uri, :text
      add :xdcc, :text
      add :raw, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :release_id, :uuid, null: false
    end

    create unique_index(:downloads, [:release_id, :resolution],
             name: "downloads_release_resolution_index",
             prefix: "subsplease"
           )

    execute("CREATE SCHEMA IF NOT EXISTS public")

    create table(:mappings, primary_key: false, prefix: "public") do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :subsplease_id, :bigint, null: false
      add :tvdb_id, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:mappings, [:subsplease_id],
             name: "mappings_unique_subsplease_id_index",
             prefix: "public"
           )

    create unique_index(:mappings, [:tvdb_id],
             name: "mappings_unique_tvdb_id_index",
             prefix: "public"
           )

    execute("CREATE SCHEMA IF NOT EXISTS subsplease")

    create table(:releases, primary_key: false, prefix: "subsplease") do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:downloads, prefix: "subsplease") do
      modify :release_id,
             references(:releases,
               column: :id,
               name: "downloads_release_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end

    alter table(:releases, prefix: "subsplease") do
      add :kind, :text, null: false
      add :name, :text, null: false
      add :episode, :text, null: false
      add :source_date, :date
      add :released_at, :utc_datetime_usec
      add :raw_time, :text
      add :raw, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :show_id, :bigint, null: false
    end

    create unique_index(:releases, [:show_id, :kind, :name],
             name: "releases_show_kind_name_index",
             prefix: "subsplease"
           )

    execute("CREATE SCHEMA IF NOT EXISTS subsplease")

    create table(:schedule_entries, primary_key: false, prefix: "subsplease") do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :slug, :text, null: false
      add :title, :text, null: false
      add :weekday, :text, null: false
      add :scheduled_time, :time, null: false
      add :image_url, :text
      add :aired, :boolean, null: false, default: false
      add :observed_at, :utc_datetime_usec, null: false
      add :raw, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :show_id, :bigint
    end

    create unique_index(:schedule_entries, [:slug, :weekday],
             name: "schedule_entries_slug_weekday_index",
             prefix: "subsplease"
           )

    execute("CREATE SCHEMA IF NOT EXISTS subsplease")

    create table(:shows, primary_key: false, prefix: "subsplease") do
      add :id, :bigint, null: false, primary_key: true
    end

    alter table(:releases, prefix: "subsplease") do
      modify :show_id,
             references(:shows,
               column: :id,
               name: "releases_show_id_fkey",
               type: :bigint,
               on_delete: :delete_all
             )
    end

    alter table(:schedule_entries, prefix: "subsplease") do
      modify :show_id,
             references(:shows,
               column: :id,
               name: "schedule_entries_show_id_fkey",
               type: :bigint,
               on_delete: :nilify_all
             )
    end

    alter table(:shows, prefix: "subsplease") do
      add :slug, :text, null: false
      add :name, :text, null: false
      add :synopsis, :text
      add :image_url, :text
      add :raw, :map
      add :fetched_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:shows, [:slug], name: "shows_unique_slug_index", prefix: "subsplease")
  end

  def down do
    drop_if_exists unique_index(:shows, [:slug],
                     name: "shows_unique_slug_index",
                     prefix: "subsplease"
                   )

    alter table(:shows, prefix: "subsplease") do
      remove :updated_at
      remove :inserted_at
      remove :fetched_at
      remove :raw
      remove :image_url
      remove :synopsis
      remove :name
      remove :slug
    end

    drop constraint(:schedule_entries, "schedule_entries_show_id_fkey", prefix: "subsplease")

    alter table(:schedule_entries, prefix: "subsplease") do
      modify :show_id, :bigint
    end

    drop constraint(:releases, "releases_show_id_fkey", prefix: "subsplease")

    alter table(:releases, prefix: "subsplease") do
      modify :show_id, :bigint
    end

    drop table(:shows, prefix: "subsplease")

    drop_if_exists unique_index(:schedule_entries, [:slug, :weekday],
                     name: "schedule_entries_slug_weekday_index",
                     prefix: "subsplease"
                   )

    drop table(:schedule_entries, prefix: "subsplease")

    drop_if_exists unique_index(:releases, [:show_id, :kind, :name],
                     name: "releases_show_kind_name_index",
                     prefix: "subsplease"
                   )

    alter table(:releases, prefix: "subsplease") do
      remove :show_id
      remove :updated_at
      remove :inserted_at
      remove :raw
      remove :raw_time
      remove :released_at
      remove :source_date
      remove :episode
      remove :name
      remove :kind
    end

    drop constraint(:downloads, "downloads_release_id_fkey", prefix: "subsplease")

    alter table(:downloads, prefix: "subsplease") do
      modify :release_id, :uuid
    end

    drop table(:releases, prefix: "subsplease")

    drop_if_exists unique_index(:mappings, [:tvdb_id],
                     name: "mappings_unique_tvdb_id_index",
                     prefix: "public"
                   )

    drop_if_exists unique_index(:mappings, [:subsplease_id],
                     name: "mappings_unique_subsplease_id_index",
                     prefix: "public"
                   )

    drop table(:mappings, prefix: "public")

    drop_if_exists unique_index(:downloads, [:release_id, :resolution],
                     name: "downloads_release_resolution_index",
                     prefix: "subsplease"
                   )

    drop table(:downloads, prefix: "subsplease")
  end
end
