defmodule Histoire.Repo.Migrations.AddTvdbMovieArtworks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS tvdb")

    create table(:movie_artworks, primary_key: false, prefix: "tvdb") do
      add :id, :bigint, null: false, primary_key: true
      add :artwork_type, :bigint
      add :language, :text
      add :image_url, :text, null: false
      add :thumbnail_url, :text
      add :includes_text, :boolean
      add :score, :float
      add :width, :bigint
      add :height, :bigint
      add :raw, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :movie_id,
          references(:movies,
            column: :id,
            name: "movie_artworks_movie_id_fkey",
            type: :bigint,
            prefix: "tvdb",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:movie_artworks, [:movie_id], prefix: "tvdb")
  end

  def down do
    drop_if_exists index(:movie_artworks, [:movie_id], prefix: "tvdb")

    drop constraint(:movie_artworks, "movie_artworks_movie_id_fkey", prefix: "tvdb")

    drop table(:movie_artworks, prefix: "tvdb")
  end
end
