defmodule Histoire.Repo.Migrations.AddSubspleaseNyaaDownloadOverrides do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS catalog")

    create table(:subsplease_nyaa_download_overrides, primary_key: false, prefix: "catalog") do
      add :subsplease_download_id,
          references(:downloads,
            column: :id,
            name: "subsplease_nyaa_download_overrides_subsplease_download_id_fkey",
            type: :uuid,
            prefix: "subsplease",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :nyaa_id,
          references(:torrents,
            column: :id,
            name: "subsplease_nyaa_download_overrides_nyaa_id_fkey",
            type: :bigint,
            prefix: "nyaa"
          ),
          null: false

      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:subsplease_nyaa_download_overrides, [:nyaa_id], prefix: "catalog")
  end

  def down do
    drop_if_exists index(:subsplease_nyaa_download_overrides, [:nyaa_id], prefix: "catalog")

    drop constraint(
           :subsplease_nyaa_download_overrides,
           "subsplease_nyaa_download_overrides_nyaa_id_fkey",
           prefix: "catalog"
         )

    drop constraint(
           :subsplease_nyaa_download_overrides,
           "subsplease_nyaa_download_overrides_subsplease_download_id_fkey",
           prefix: "catalog"
         )

    drop table(:subsplease_nyaa_download_overrides, prefix: "catalog")
  end
end
