defmodule Histoire.Repo.Migrations.MoveCrossSourceMatchesToCatalog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS catalog")
    execute("ALTER TABLE public.mappings SET SCHEMA catalog")
    execute("ALTER TABLE catalog.mappings RENAME TO subsplease_tvdb_show_matches")
    execute("ALTER INDEX catalog.mappings_pkey RENAME TO subsplease_tvdb_show_matches_pkey")

    execute(
      "ALTER INDEX catalog.mappings_unique_subsplease_id_index RENAME TO subsplease_tvdb_show_matches_unique_subsplease_id_index"
    )

    execute(
      "ALTER INDEX catalog.mappings_tvdb_id_index RENAME TO subsplease_tvdb_show_matches_tvdb_id_index"
    )
  end

  def down do
    execute(
      "ALTER INDEX catalog.subsplease_tvdb_show_matches_tvdb_id_index RENAME TO mappings_tvdb_id_index"
    )

    execute(
      "ALTER INDEX catalog.subsplease_tvdb_show_matches_unique_subsplease_id_index RENAME TO mappings_unique_subsplease_id_index"
    )

    execute("ALTER INDEX catalog.subsplease_tvdb_show_matches_pkey RENAME TO mappings_pkey")
    execute("ALTER TABLE catalog.subsplease_tvdb_show_matches RENAME TO mappings")
    execute("ALTER TABLE catalog.mappings SET SCHEMA public")
    execute("DROP SCHEMA catalog")
  end
end
