defmodule Histoire.Repo.Migrations.AddLlmTvdbMatching do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mappings, prefix: "public") do
      add :candidate_tvdb_id, :bigint
      add :status, :text, null: false, default: "pending"
      add :match_confidence, :float
      add :match_reasoning, :text
      add :match_method, :text
      add :matched_at, :utc_datetime_usec
      add :last_attempted_at, :utc_datetime_usec
      add :last_error, :text
      add :attempts, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:mappings, prefix: "public") do
      remove :attempts
      remove :last_error
      remove :last_attempted_at
      remove :matched_at
      remove :match_method
      remove :match_reasoning
      remove :match_confidence
      remove :status
      remove :candidate_tvdb_id
    end
  end
end
