defmodule Histoire.Repo.Migrations.AddNyaaTorrentCache do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS nyaa")

    create table(:files, primary_key: false, prefix: "nyaa") do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :path, :text, null: false
      add :size, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :torrent_id, :bigint, null: false
    end

    create unique_index(:files, [:torrent_id, :path],
             name: "files_torrent_path_index",
             prefix: "nyaa"
           )

    create index(:files, [:torrent_id], prefix: "nyaa")

    execute("CREATE SCHEMA IF NOT EXISTS nyaa")

    create table(:torrents, primary_key: false, prefix: "nyaa") do
      add :id, :bigint, null: false, primary_key: true
    end

    alter table(:files, prefix: "nyaa") do
      modify :torrent_id,
             references(:torrents,
               column: :id,
               name: "files_torrent_id_fkey",
               type: :bigint,
               on_delete: :delete_all
             )
    end

    alter table(:torrents, prefix: "nyaa") do
      add :title, :text, null: false
      add :page_url, :text, null: false
      add :magnet_uri, :text, null: false
      add :fetched_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:torrents, prefix: "nyaa") do
      remove :updated_at
      remove :inserted_at
      remove :fetched_at
      remove :magnet_uri
      remove :page_url
      remove :title
    end

    drop constraint(:files, "files_torrent_id_fkey", prefix: "nyaa")

    alter table(:files, prefix: "nyaa") do
      modify :torrent_id, :bigint
    end

    drop table(:torrents, prefix: "nyaa")

    drop_if_exists index(:files, [:torrent_id], prefix: "nyaa")

    drop_if_exists unique_index(:files, [:torrent_id, :path],
                     name: "files_torrent_path_index",
                     prefix: "nyaa"
                   )

    drop table(:files, prefix: "nyaa")
  end
end
