defmodule AnimeData.Repo.Migrations.AllowSharedTvdbMappings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:mappings, [:tvdb_id],
                     name: "mappings_unique_tvdb_id_index",
                     prefix: "public"
                   )
  end

  def down do
    create unique_index(:mappings, [:tvdb_id],
             name: "mappings_unique_tvdb_id_index",
             prefix: "public"
           )
  end
end
