defmodule Histoire.Repo.Migrations.AddTvdbMoviesAndIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:artworks, [:series_id], prefix: "tvdb")

    alter table(:mappings, prefix: "public") do
      add :tvdb_type, :text
      add :candidate_tvdb_type, :text
    end

    execute("UPDATE public.mappings SET tvdb_type = 'series' WHERE tvdb_id IS NOT NULL")

    execute(
      "UPDATE public.mappings SET candidate_tvdb_type = 'series' WHERE candidate_tvdb_id IS NOT NULL"
    )

    create index(:mappings, [:tvdb_id], prefix: "public")

    execute("CREATE SCHEMA IF NOT EXISTS tvdb")

    create table(:movies, primary_key: false, prefix: "tvdb") do
      add :id, :bigint, null: false, primary_key: true
      add :name, :text, null: false
      add :slug, :text
      add :overview, :text
      add :image_url, :text
      add :first_released, :date
      add :year, :text
      add :status_id, :bigint
      add :status_name, :text
      add :original_country, :text
      add :original_language, :text
      add :runtime, :bigint
      add :score, :float
      add :raw, :map
      add :fetched_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:schedule_entries, [:show_id], prefix: "subsplease")

    create index(:seasons, [:series_id], prefix: "tvdb")
  end

  def down do
    drop_if_exists index(:seasons, [:series_id], prefix: "tvdb")

    drop_if_exists index(:schedule_entries, [:show_id], prefix: "subsplease")

    drop table(:movies, prefix: "tvdb")

    drop_if_exists index(:mappings, [:tvdb_id], prefix: "public")

    alter table(:mappings, prefix: "public") do
      remove :candidate_tvdb_type
      remove :tvdb_type
    end

    drop_if_exists index(:artworks, [:series_id], prefix: "tvdb")
  end
end
