defmodule AnimeData.Repo.Migrations.AddTvdbSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS tvdb")

    create table(:artworks, primary_key: false, prefix: "tvdb") do
      add :id, :bigint, null: false, primary_key: true
      add :artwork_type, :bigint
      add :language, :text
      add :image_url, :text, null: false
      add :thumbnail_url, :text
      add :includes_text, :boolean
      add :score, :float
      add :width, :bigint
      add :height, :bigint
      add :raw, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :series_id, :bigint, null: false
    end

    execute("CREATE SCHEMA IF NOT EXISTS tvdb")

    create table(:seasons, primary_key: false, prefix: "tvdb") do
      add :id, :bigint, null: false, primary_key: true
      add :number, :bigint
      add :name, :text
      add :image_url, :text
      add :overview, :text
      add :type_id, :bigint
      add :type_name, :text
      add :raw, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :series_id, :bigint, null: false
    end

    execute("CREATE SCHEMA IF NOT EXISTS tvdb")

    create table(:series, primary_key: false, prefix: "tvdb") do
      add :id, :bigint, null: false, primary_key: true
    end

    alter table(:artworks, prefix: "tvdb") do
      modify :series_id,
             references(:series,
               column: :id,
               name: "artworks_series_id_fkey",
               type: :bigint,
               on_delete: :delete_all
             )
    end

    alter table(:seasons, prefix: "tvdb") do
      modify :series_id,
             references(:series,
               column: :id,
               name: "seasons_series_id_fkey",
               type: :bigint,
               on_delete: :delete_all
             )
    end

    alter table(:series, prefix: "tvdb") do
      add :name, :text, null: false
      add :slug, :text
      add :overview, :text
      add :image_url, :text
      add :first_aired, :date
      add :last_aired, :date
      add :next_aired, :date
      add :year, :text
      add :status_id, :bigint
      add :status_name, :text
      add :original_country, :text
      add :original_language, :text
      add :average_runtime, :bigint
      add :score, :float
      add :raw, :map
      add :fetched_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:series, prefix: "tvdb") do
      remove :updated_at
      remove :inserted_at
      remove :fetched_at
      remove :raw
      remove :score
      remove :average_runtime
      remove :original_language
      remove :original_country
      remove :status_name
      remove :status_id
      remove :year
      remove :next_aired
      remove :last_aired
      remove :first_aired
      remove :image_url
      remove :overview
      remove :slug
      remove :name
    end

    drop constraint(:seasons, "seasons_series_id_fkey", prefix: "tvdb")

    alter table(:seasons, prefix: "tvdb") do
      modify :series_id, :bigint
    end

    drop constraint(:artworks, "artworks_series_id_fkey", prefix: "tvdb")

    alter table(:artworks, prefix: "tvdb") do
      modify :series_id, :bigint
    end

    drop table(:series, prefix: "tvdb")

    drop table(:seasons, prefix: "tvdb")

    drop table(:artworks, prefix: "tvdb")
  end
end
